name: Deploy Backend

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t cashl/dermetric_web_server:${{ github.sha }} ./backend
      - name: Push Docker Image
        run: docker push cashl/dermetric_web_server:${{ github.sha }}
